services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
       MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
