spring.application.name=product-service
spring.data.mongodb.uri=mongodb://admin:835134511@localhost:27017/productdb?authSource=admin
server.port=0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

logging.level.org.springframework.security=TRACE
spring.security.oauth2.resource-server.jwt.issuer-uri=http://localhost:8181/realms/spring-boot-microservices-realm
