spring.application.name=product-service
spring.data.mongodb.uri=mongodb://admin:835134511@localhost:27017/productdb?authSource=admin
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
