services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb-inventory
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: inventory_database
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
